/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.53
 * Generated at: 2022-01-28 08:12:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.board.example.dto.*;

public final class join_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("jar:file:/D:/sts_lyr/sts4_teacher_trip/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/web03/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/head.jsp", Long.valueOf(1642642296772L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/menu.jsp", Long.valueOf(1642642985037L));
    _jspx_dependants.put("/WEB-INF/views/member/../include/footer.jsp", Long.valueOf(1642643121986L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1640568487443L));
    _jspx_dependants.put("jar:file:/D:/sts_lyr/sts4_teacher_trip/.metadata/.plugins/org.eclipse.wst.server.core/tmp2/wtpwebapps/web03/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("com.board.example.dto");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>회원가입</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');

	MemberDTO member = (MemberDTO) session.getAttribute("member");

      out.write("\r\n");
      out.write("    <meta charset=\"UTF-8\">\r\n");
      out.write("    <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\r\n");
      out.write("    <meta name=\"viewport\" content=\"width=device-width, initial-scale=1.0\">\r\n");
      out.write("    <title>여수관광문화</title>\r\n");
      out.write("    <!-- 파비콘-->\r\n");
      out.write("    <link rel=\"icon\" type=\"image/png\" sizes=\"32x32\" href=\"/img/hd_logo.png\">\r\n");
      out.write("    <!-- 메타포-->\r\n");
      out.write("    <meta name=\"title\" content=\"여수 관광문화 홈페이지\">\r\n");
      out.write("    <meta name=\"description\" content=\"전라남도 여수시 관광안내, 관광명소, 문화유적, 축제문화행사, 숙박 등 정보 제공\">\r\n");
      out.write("    <meta name=\"keywords\" content=\"여수관광안내, 돌산갓김치, 게장백반, 서대회, 여수한정식, 갯장어회, 갯장어 샤브샤브, 굴구이, 장어구이, 갈치조림, 새조개샤브샤브, 전어회, 전어구이,오동도, 거문도,백도,향일암, 금오도비렁길, 비렁길, 여수세계박람회장, 진남관, 충무공, 이순신, 여수밤바다, 산단야경, 영취산, 영취산진달래, 진달래, 해상케이블카, 이순신대교, 거북선, 거북선축제, 국제청소년축제, 국제범선축제, 여자만, 여자만갯벌, 진달래체험,갯벌노을체험,향일암일출\">\r\n");
      out.write("    <!-- 오픈그래프-->\r\n");
      out.write("    <meta property=\"og:url\" content=\"http://www.yeosu.go.kr/tour/tour\">\r\n");
      out.write("    <meta property=\"og:type\" content=\"article\">\r\n");
      out.write("    <meta property=\"og:image\" content=\"http://www.yeosu.go.kr/contents/fb_ystour_logo.png\">\r\n");
      out.write("    <meta property=\"og:site_name\" content=\"여수관광문화\">\r\n");
      out.write("    <meta property=\"og:article:author\" content=\"https://www.facebook.com/goystour\">\r\n");
      out.write("    <meta property=\"og:article:publisher\" content=\"https://www.facebook.com/goystour\">\r\n");
      out.write("    <meta property=\"og:article:thumbnailUrl\" content=\"http://www.yeosu.go.kr/contents/fb_ystour_logo.png\">\r\n");
      out.write("    <meta property=\"og:article:author\" content=\"생명의 푸르름 가득한, 여수관광문화\">\r\n");
      out.write("    <meta property=\"og:article:author:url\" content=\"http://www.yeosu.go.kr/tour/\">\r\n");
      out.write("    <!-- 폰트로딩-->\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.googleapis.com\">\r\n");
      out.write("    <link rel=\"preconnect\" href=\"https://fonts.gstatic.com\" crossorigin>\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css2?family=Noto+Sans+KR&display=swap\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=East+Sea+Dokdo:400\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Black+Han+Sans:400\" rel=\"stylesheet\">\r\n");
      out.write("    <link href=\"https://fonts.googleapis.com/css?family=Song+Myung:400\" rel=\"stylesheet\">\r\n");
      out.write("   <!-- 외부 스타일 연결-->\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"common.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"grid.css\">\r\n");
      out.write("   <link rel=\"stylesheet\" href=\"jquery.bxslider/jquery.bxslider.css\">\r\n");
      out.write("\r\n");
      out.write("   <style>\r\n");
      out.write("    /*font-family: 'Noto Sans KR', sans-serif;*/\r\n");
      out.write("    /*font-family: 'East Sea Dokdo', sans-serif;*/\r\n");
      out.write("\r\n");
      out.write("    /*font-family: 'Black Han Sans', sans-serif;*/\r\n");
      out.write("    /*font-family: 'Song Myung', sans-serif;*/\r\n");
      out.write("    /*font-family: 'East Sea Dokdo', sans-serif;*/\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("<style> \r\n");
      out.write("\r\n");
      out.write("    #item1 { background-image: url(\"./img/event1.jpg\");}\r\n");
      out.write("    #item2 { background-image: url(\"./img/event2.jpg\");}\r\n");
      out.write("    #item3 { background-image: url(\"./img/event3.jsp\");}\r\n");
      out.write("    #item4 { background-image: url(\"./img/event4.jsp\");}\r\n");
      out.write("    #item5 { background-image: url(\"./img/event5.jpg\");}\r\n");
      out.write("\r\n");
      out.write("   .content { clear:both; width: 100%; min-height:2000px; }   \r\n");
      out.write("    .vs { clear:both; width: 100%; position: relative; overflow-x:hidden; } \r\n");
      out.write("    .vs .img_box { width: 400%;}\r\n");
      out.write("    .vs .img_box li { width: 25%; float:left; position:relative; } \r\n");
      out.write("    .vs .img_box li a { display: block; position: relative; } \r\n");
      out.write("    .vs .img_box li .vs_img { display:block; width: 100%; height:760px; margin: 0 auto; }\r\n");
      out.write("    .vs .img_box .tit_box { position:absolute; top: 28px; left: 0; z-index:10; \r\n");
      out.write("    padding: 60px 280px; color: #fff; text-align: center; }\r\n");
      out.write("    .vs .img_box .vs_tit { font-size: 100px; font-family: 'Song Myung';\r\n");
      out.write("    font-weight: 200; text-shadow: 2px 2px 2px #333; }\r\n");
      out.write("    .vs .img_box .vs_com {font-size: 18px; text-shadow: -1px -1px 2px rgb(44, 44, 44);  }\r\n");
      out.write("\r\n");
      out.write("    .btn_box li { display:none; } \r\n");
      out.write("    .ra { display:none; }\r\n");
      out.write("    #ra1:checked ~ .btn_box li.item1 { display:block; }\r\n");
      out.write("    #ra2:checked ~ .btn_box li.item2 { display:block; }  \r\n");
      out.write("    #ra3:checked ~ .btn_box li.item3 { display:block; }  \r\n");
      out.write("    #ra4:checked ~ .btn_box li.item4 { display:block; }  \r\n");
      out.write("\r\n");
      out.write("    .img_box { width: 400%; transition-duration: 2.2s; }\r\n");
      out.write("    .img_box li { width: 25%; float:left; }\r\n");
      out.write("    #ra1:checked ~ .img_box { margin-left: 0; }\r\n");
      out.write("    #ra2:checked ~ .img_box { margin-left:-100%; }\r\n");
      out.write("    #ra3:checked ~ .img_box { margin-left:-200%; }\r\n");
      out.write("    #ra4:checked ~ .img_box { margin-left:-300%; }\r\n");
      out.write("    .btn_box li label { display:block; width: 100px; height: 100px; position:absolute; \r\n");
      out.write("        top:330px; z-index:10; text-indent:-10000px; background-repeat: no-repeat; }\r\n");
      out.write("    .btn_box li label.prev { left:60px; background-image: url(./img/le.png)}\r\n");
      out.write("    .btn_box li label.next { right:60px; background-image: url(./img/ri.png)}\r\n");
      out.write("\r\n");
      out.write("   .donbag {display: block; clear: both; position: absolute; width: 300px; top: 600px; left: 50%; margin-left: 50px; margin-left: -160px; z-index: 100;} \r\n");
      out.write("\r\n");
      out.write("    #page1 { padding-top: 100px; position:relative; background-color: rgb(248, 186, 186); height: 800px; background-image: url(./img/dong_pn.png); }\r\n");
      out.write("    .pg_tit1 { font-family: 'Song Myung'; font-size: 50px; padding-bottom: 15px;  }\r\n");
      out.write("    #page2 { clear: both; width: 100%; height: 50vh; padding-top: 30px; background-color: rgb(127, 196, 136); background-image: url(./img/back1.png); }\r\n");
      out.write("    .more { display:block; background-image: url(./img/youtube.png); text-indent:-10000px; width: 300px; \r\n");
      out.write("        background-repeat: no-repeat; background-position:center center; float: right; z-index:10; padding-top: 30px;}\r\n");
      out.write("    .youtube { clear: both;  width: 100%; padding-bottom: 50px; }\r\n");
      out.write("    .youtube2 { clear: both; float: left;}\r\n");
      out.write("    .youtube li { float: left; }\r\n");
      out.write("    .youtube li .v { width: 350px; height: 300px; padding: 25px;}\r\n");
      out.write("    .youtube2 .t { padding-left: 72px; padding-right: 101px; float: left; font-size: 16px;}\r\n");
      out.write("    .icon_lst li a {clear: both;}\r\n");
      out.write("    .new_tit { font-family: 'Song Myung'; font-size: 50px; }\r\n");
      out.write("\r\n");
      out.write("    .map { margin: 0 auto; width: 100%; }\r\n");
      out.write("    .map_img {float: left;}\r\n");
      out.write("    .map_com {float: right; background-color: rgb(255,239,115); padding: 20px;  }\r\n");
      out.write("\r\n");
      out.write("    #page3 { background-color: rgb(115,193,225); clear: both; width: 100%; height: 100vh; background-image: url(./img/back2.png);}\r\n");
      out.write("    .pg_tit { font-family: 'Song Myung'; font-size: 50px; margin: 20px auto; padding-left: 500px; padding-top: 30px;}\r\n");
      out.write("    .map_img { display:block; width: 100%; }\r\n");
      out.write("    .new_lst { width: 100%; }\r\n");
      out.write("    .col6 { float: left; }\r\n");
      out.write("    \r\n");
      out.write("</style>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("    #item8 { background-color: rgb(109 203 223);}\r\n");
      out.write("    #item9 { background-image: url(\"./img/tree.jpg\");}\r\n");
      out.write("    #item10 { background-image: url(\"./img/sun.jpg\");}\r\n");
      out.write("    #item11 { background-color: #fff; }\r\n");
      out.write("\r\n");
      out.write("    .ptit_box { width: 440px; height: 440px; background-color:#05a4a6; color:#fff; \r\n");
      out.write("    text-align: center; padding-top: 330px; box-sizing: border-box; position:absolute; left: 50%; margin-left: -222px; border-radius:50%; margin-top: -492px;   }\r\n");
      out.write("    .pg_tit3 {  font-family: 'Song Myung'; font-size:55px; font-weight:600; margin-top: 210px; color: black;}\r\n");
      out.write("    .pg_tit4 {  font-family: 'Song Myung'; font-size:24px; font-weight:300; color: rgb(43, 43, 43); }\r\n");
      out.write("    .ra0 { display:none; }\r\n");
      out.write("    #page4 .ptit_box { background-color: #00436f;}\r\n");
      out.write("    #item6 { width: 400%;  transition-delay:0.05s; \r\n");
      out.write("    transition-duration:0.6s; }\r\n");
      out.write("    #item6 li { width: 25%; float:left; }\r\n");
      out.write("    .thumb_vs_wrap { position:absolute; right:0; bottom: 0; overflow:hidden; width: 300px; height: 277px; }\r\n");
      out.write("    #item7 { width: 400%; margin-left: 0; transition-delay:0.05s; \r\n");
      out.write("    transition-duration:0.6s; }\r\n");
      out.write("    #item7 li { width: 25%; float:left; }\r\n");
      out.write("    #item7 li label { display:block; width: 18px; height: 36px; \r\n");
      out.write("    background-repeat: no-repeat; background-position:center center; position:absolute; bottom:100px; text-indent:-10000px; cursor:pointer; }\r\n");
      out.write("    #item7 li label.lb1 { left:24px; background-image: url(\"./img/le.png\"); }\r\n");
      out.write("    #item7 li label.lb2 { right:24px; background-image: url(\"./img/ri.png\"); }\r\n");
      out.write("    #item7 .tbox { width: 140px; height: 140px; clear:both;overflow:hidden;   margin:20px auto; top: 50px;  border-radius:75px; border:3px solid #fff; }\r\n");
      out.write("    .thumb_vs_wrap #item7 li label { display:none; }\r\n");
      out.write("    .ra { display:none; }\r\n");
      out.write("    #ra5:checked ~ .thumb_vs_wrap #item7 .item1 label { display:block; }\r\n");
      out.write("    #ra6:checked ~ .thumb_vs_wrap #item7 .item2 label { display:block; }\r\n");
      out.write("    #ra7:checked ~ .thumb_vs_wrap #item7 .item3 label { display:block; }\r\n");
      out.write("    #ra8:checked ~ .thumb_vs_wrap #item7 .item4 label { display:block; }\r\n");
      out.write("    #ra5:checked ~ .thumb_vs_wrap #item7 { margin-left: 0; }\r\n");
      out.write("    #ra6:checked ~ .thumb_vs_wrap #item7 { margin-left:-100%; }\r\n");
      out.write("    #ra7:checked ~ .thumb_vs_wrap #item7 { margin-left:-200%; }\r\n");
      out.write("    #ra8:checked ~ .thumb_vs_wrap #item7 { margin-left:-300%; }\r\n");
      out.write("    #ra5:checked ~ #item6 { margin-left: 0; }\r\n");
      out.write("    #ra6:checked ~ #item6 { margin-left:-100%; }\r\n");
      out.write("    #ra7:checked ~ #item6 { margin-left:-200%; }\r\n");
      out.write("    #ra8:checked ~ #item6 { margin-left:-300%; }\r\n");
      out.write("    .col_vs_tit_box { position:absolute; top: 0; left: 0; }\r\n");
      out.write("    .col_vs_tit { clear:both; width: 100%;  padding-top: 50px;  }\r\n");
      out.write("    .col_vs_tit span { display:block; font-family: 'TTTogether';  font-weight:400; \r\n");
      out.write("padding-left:120px; font-size:48px;}\r\n");
      out.write("    .col_vs_tit .row1 { color:#00436f; font-family: 'Song Myung'; font-weight: 600; text-shadow: 0px 0px 3px rgb(255, 255, 255)}\r\n");
      out.write("    .col_vs_tit .row2 { color:#007bbf; font-family: 'Song Myung'; font-weight: 600; text-shadow: 0px 0px 3px rgb(255, 255, 255);}\r\n");
      out.write("    .col_vs_com { padding-left: 120px; padding-top: 5px; font-size: 25px; font-family: 'Song Myung'; font-weight: 500; text-shadow: 0px 0px 3px rgb(255, 255, 255);}\r\n");
      out.write("    #item8 .col_tit, #item9 .col_tit { line-height: 1.6; } \r\n");
      out.write("    #item9 .col_com img { border:2px solid #fff; border-radius:100px; margin-left: 48px;}\r\n");
      out.write("    #item8 .col_com img { margin-top: -38px; margin-left: 20px; }\r\n");
      out.write("    #page2 .col_com { clear:both; float:none; width:auto; margin:0px auto; }\r\n");
      out.write("    .col_tit.black_txt { color:#000; line-height: 1.6; padding-top: 12px; }\r\n");
      out.write("    .col_tit.black_txt:after { background-color: #00b2a3; }\r\n");
      out.write("    #item11 { position:relative; }\r\n");
      out.write("    #item11 .link_box { position:absolute; bottom: 0; left: 0; width: 100%; }\r\n");
      out.write("    #item11 .link_box li { display:block; width: 50%; float:left; }\r\n");
      out.write("    #item11 .link_box li a { display:block; line-height: 65px; height: 65px; color:#222; background-color: #00b2a3; padding-left:64px; font-size:14px; border-top:1px solid #fff; border-left:1px solid #fff; \r\n");
      out.write("    background-repeat: no-repeat; background-position:18px center; }\r\n");
      out.write("    #item11 .link_box li:nth-child(2n+1) a { border-left:0px; }\r\n");
      out.write("    #item11 .link_box li.item1 a { background-image: url(\"./source/pg2_icon1.png\"); }\r\n");
      out.write("    #item11 .link_box li.item2 a { background-image: url(\"./source/pg2_icon2.png\"); }\r\n");
      out.write("    #item11 .link_box li.item3 a { background-image: url(\"./source/pg2_icon3.png\"); }\r\n");
      out.write("    #item11 .link_box li.item4 a { background-image: url(\"./source/pg2_icon4.png\"); }\r\n");
      out.write("\r\n");
      out.write("    #page3 .ptit_box { background-color: #007bbf;}\r\n");
      out.write("     .col_tit { color:#fff; text-align: center; line-height:3; width: 100%; clear:both; margin-top: 28px; }\r\n");
      out.write("    .col_tit:after { content:\"\"; display:block; width: 40px; height: 2px; \r\n");
      out.write("background-color: #fff; clear:both; margin:0px auto; margin-bottom: 20px; }\r\n");
      out.write("    .col_com { color:#fff; padding: 20px 60px; font-size:20px; text-align: center;}\r\n");
      out.write("    \r\n");
      out.write("    #page4 .col_link { display:block;  clear:both; float:none; width: 38px; height: 38px; \r\n");
      out.write("    margin: 10px auto; background-image: url(\"./source/family-arrow.png\");\r\n");
      out.write("    border-radius:21px; border:2px solid #fff;  text-indent:-10000px;\r\n");
      out.write("background-repeat: no-repeat; background-position:center center; \r\n");
      out.write("    transform: rotate(90deg); }\r\n");
      out.write("\r\n");
      out.write("   .page4top{ margin-top: 200px; }\r\n");
      out.write("\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("<div class=\"wrap\">\r\n");
      out.write("	");
      out.write("\n");
      out.write("\n");
      out.write("<header class=\"hd fix\">\n");
      out.write("            <div class=\"hd_wrap\">\n");
      out.write("            ");
      if (_jspx_meth_c_005fset_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/\" class=\"logo\">\n");
      out.write("                    <img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/logo.png\" alt=\"로고\">\n");
      out.write("                </a>\n");
      out.write("                <nav class=\"tnb\">\n");
      out.write("                    <ul>        \n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("					");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\n");
      out.write("                    </ul>\n");
      out.write("                </nav>\n");
      out.write("                <nav class=\"gnb\">\n");
      out.write("                    <ul>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"sub1_1.html\" class=\"dp1\">관광명소</a>\n");
      out.write("                            <ul class=\"sub\">\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub1_1.html\">오동도</a></li>\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub1_2.html\">진남관</a></li>\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub1_3.html\">거문도백도</a></li>\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub1_4.html\">여수해상케이블카</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\" class=\"dp1\">문화/축제</a>\n");
      out.write("                            <ul class=\"sub\">\n");
      out.write("                                <li><a href=\"\">낭만버스킹</a></li>\n");
      out.write("                                <li><a href=\"\">여수거북선축제</a></li>\n");
      out.write("                                <li><a href=\"\">여수불꽃축제</a></li>\n");
      out.write("                                <li><a href=\"\">향일 일출제</a></li>                           \n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li> \n");
      out.write("                            <a href=\"\" class=\"dp1\">여수대표음식</a>\n");
      out.write("                            <ul class=\"sub\">\n");
      out.write("                                <li><a href=\"\">돌산갓김치</a></li>\n");
      out.write("                                <li><a href=\"\">게장백반</a></li>\n");
      out.write("                                <li><a href=\"\">여수한정식</a></li>\n");
      out.write("                                <li><a href=\"\">굴구이</a></li>                              \n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"\" class=\"dp1\">여행/체험</a>\n");
      out.write("                            <ul class=\"sub\">\n");
      out.write("                                <li><a href=\"\">자전거코스</a></li>\n");
      out.write("                                <li><a href=\"\">걷기여행</a></li>                            \n");
      out.write("                                <li><a href=\"\">이순신코스</a></li>\n");
      out.write("                                <li><a href=\"\">여수낭만버스</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                        <li>\n");
      out.write("                            <a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub5_1.html\" class=\"dp1\">관광안내</a>\n");
      out.write("                            <ul class=\"sub\">\n");
      out.write("                                <li><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/sub5_1.html\">관광소식</a></li>\n");
      out.write("                                <li><a href=\"\">관광웹툰</a></li>\n");
      out.write("                                <li><a href=\"\">관광캐릭터</a></li>\n");
      out.write("                                <li><a href=\"\">여수여행사</a></li>\n");
      out.write("                            </ul>\n");
      out.write("                        </li>\n");
      out.write("                    </ul>\n");
      out.write("                </nav> \n");
      out.write("            </div>    \n");
      out.write("        </header> \n");
      out.write("\n");
      out.write("<hr>");
      out.write("\r\n");
      out.write("	<section class=\"content\">\r\n");
      out.write("		<h2>회원 가입 폼</h2>\r\n");
      out.write("	    <div class=\"reg_form_box\">\r\n");
      out.write("	        <form method=\"post\" action=\"/member/joinPro.do\" class=\"form\">\r\n");
      out.write("	        	<table class=\"table\">\r\n");
      out.write("		        	<tbody>\r\n");
      out.write("			            <tr class=\"reg_row\">\r\n");
      out.write("			                <th><label for=\"userid\" class=\"reg-label\">*아이디</label></th>\r\n");
      out.write("			                <td class=\"reg_input\">\r\n");
      out.write("			                   <input type=\"text\" id=\"userid\" name=\"userid\" class=\"reg-control\" maxlength=\"13\" required />\r\n");
      out.write("			               </td>\r\n");
      out.write("			           </tr>\r\n");
      out.write("			           <tr class=\"reg_row\">\r\n");
      out.write("			               <th><label for=\"passwd\" class=\"reg-label\">*비밀번호</label></th>\r\n");
      out.write("			               <td class=\"reg_input\">\r\n");
      out.write("			                   <input type=\"password\" id=\"passwd\" name=\"passwd\" class=\"reg-control\" maxlength=\"20\" required />\r\n");
      out.write("			                   <!-- <input type=\"hidden\" name=\"passwd\" value=\"\"> -->\r\n");
      out.write("			               </td>\r\n");
      out.write("			           </tr>\r\n");
      out.write("			           <tr class=\"reg_row\">\r\n");
      out.write("			               <th><label for=\"userPwChk\" class=\"reg-label\">*비밀번호 확인 </label></th>\r\n");
      out.write("			               <td class=\"reg_input\">\r\n");
      out.write("			                   ​<input type=\"password\" id=\"userPwChk\" name=\"passwds2\" class=\"reg-control\" maxlength=\"20\" required />\r\n");
      out.write("			               </td>\r\n");
      out.write("			           </tr>\r\n");
      out.write("			           <tr class=\"reg_row\">\r\n");
      out.write("			               <th><label for=\"name\" class=\"reg-label\">*이름</label></th>\r\n");
      out.write("			               <td class=\"reg_input\">\r\n");
      out.write("			                    <input type=\"text\" id=\"name\" name=\"name\" class=\"reg-control\" maxlength=\"13\" required />\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr class=\"reg_row\">\r\n");
      out.write("			                <th><label for=\"email\" class=\"reg-label\">*이메일</label></th>\r\n");
      out.write("			                <td class=\"reg_input\">\r\n");
      out.write("			                    <input type=\"text\" id=\"email\" name=\"email\" class=\"reg-control\" maxlength=\"50\" />\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr class=\"reg_row\">\r\n");
      out.write("			                <th><label for=\"phone\" class=\"reg-label\">*전화번호, '-' 입력 제외 </label></th>\r\n");
      out.write("			                <td class=\"reg_input\">\r\n");
      out.write("			                    <input type=\"text\" id=\"phone\" name=\"phone\" class=\"reg-control\" maxlength=\"15\" />\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr class=\"reg_row\">\r\n");
      out.write("			                <th><label class=\"reg-label\" id=\"birth\">*생년월일</label></th>\r\n");
      out.write("			                <td class=\"reg_input\">\r\n");
      out.write("			                    <input type=\"text\" id=\"birth\" name=\"birth\" class=\"reg-control\" maxlength=\"8\" />\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("			            <tr class=\"reg_row\">\r\n");
      out.write("			                <td class=\"reg_btn_group\" colspan=\"2\">\r\n");
      out.write("			                    <input type=\"submit\" class=\"btn btn-primary\" id=\"reg_form_btn\" value=\"회원가입\" />\r\n");
      out.write("			                    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;\r\n");
      out.write("			                    <input type=\"reset\" class=\"btn btn-primary\" id=\"reg_form_btn2\" value=\"취소\" />\r\n");
      out.write("			                </td>\r\n");
      out.write("			            </tr>\r\n");
      out.write("		            </tbody>\r\n");
      out.write("	            </table>\r\n");
      out.write("	        </form>\r\n");
      out.write("	        <script src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/include/js/crypto-js.min.js\"></script>\r\n");
      out.write("	        <script>\r\n");
      out.write("	        function cription(f) {\r\n");
      out.write("	            var CryptoJS = CryptoJS;\r\n");
      out.write("	        	var data = f.passwds.value;\r\n");
      out.write("	            // Encrypt\r\n");
      out.write("	            var ciphertext = CryptoJS.AES.encrypt(JSON.stringify(data), '456').toString();\r\n");
      out.write("	            f.passwd.value = ciphertext;\r\n");
      out.write("	            console.log(ciphertext);\r\n");
      out.write("	            f.submit();\r\n");
      out.write("	            return false;\r\n");
      out.write("	            // Decrypt\r\n");
      out.write("	            var bytes  = CryptoJS.AES.decrypt(ciphertext, '456');\r\n");
      out.write("	            var decryptedData = JSON.parse(bytes.toString(CryptoJS.enc.Utf8));\r\n");
      out.write("	          \r\n");
      out.write("	            console.log(decryptedData); \r\n");
      out.write("	        }\r\n");
      out.write("	        </script>\r\n");
      out.write("	    </div>\r\n");
      out.write("	 </section>   \r\n");
      out.write("	");
      out.write("\r\n");
      out.write("<footer class=\"ft fix\">\r\n");
      out.write("            <nav class=\"fnb\">\r\n");
      out.write("                <ul class=\"fnb_fr\">\r\n");
      out.write("                    <li><a href=\"\">개인정보처리방침</a></li>\r\n");
      out.write("                    <li><a href=\"\">사진갤러리</a></li>\r\n");
      out.write("                    <li><a href=\"\">업소등록</a></li>\r\n");
      out.write("                    <li><a href=\"\">로그인</a></li>\r\n");
      out.write("                    <li><a href=\"\">여수시청</a></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </nav>\r\n");
      out.write("            <div class=\"ft_wrap\">\r\n");
      out.write("                <div class=\"copyright\">\r\n");
      out.write("                    <p class=\"addr\"><br>[59675] 전남 여수시 시청로 1 (학동)시청콜센터 : 1899-2012 / 관광통역안내 : 1330 / E-mail:ksu2020@korea.kr</p>\r\n");
      out.write("                    <p class=\"copy\">COPYRIGHT(C) 2015 BY YEOSUCITY. ALL RIGHT RESERVED.</p>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"wa\"><img src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/img/ft_logo.png\" alt=\"여수로고\"></div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </footer>  ");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/../include/head.jsp(6,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("path");
      // /WEB-INF/views/member/../include/head.jsp(6,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/head.jsp(6,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fset_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f1 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f1_reused = false;
    try {
      _jspx_th_c_005fset_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f1.setParent(null);
      // /WEB-INF/views/member/../include/menu.jsp(6,12) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setVar("path");
      // /WEB-INF/views/member/../include/menu.jsp(6,12) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f1.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/../include/menu.jsp(6,12) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f1 = _jspx_th_c_005fset_005f1.doStartTag();
      if (_jspx_th_c_005fset_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f1);
      _jspx_th_c_005fset_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/../include/menu.jsp(12,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("                        <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/join.do\">회원가입</a></li>    \n");
          out.write("                        <li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/login.do\">로그인</a></li>\n");
          out.write("                        <li><a href=\"https://www.badatime.com/41.html?idx=41\">물때표</a></li>\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/../include/menu.jsp(17,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("						<li>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님</li>	\n");
          out.write("						<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/mypage.do?userid=");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.getUserid() }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" class=\"dp1\">마이페이지</a></li>\n");
          out.write("						<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/logout.do\" class=\"dp1\">로그아웃</a></li>\n");
          out.write("						<li><a href=\"https://www.badatime.com/41.html?idx=41\">물때표</a></li>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f2_reused = false;
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/views/member/../include/menu.jsp(23,5) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.userid == 'admin'}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("	\n");
          out.write("						<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/board/list.do\" class=\"dp1\">게시판 관리</a></li>\n");
          out.write("						<li><a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${path}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/member/list.do\" class=\"dp1\">회원 관리</a></li>\n");
          out.write("						<li><a href=\"https://www.badatime.com/41.html?idx=41\">물때표</a></li>\n");
          out.write("					");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
      _jspx_th_c_005fif_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
    }
    return false;
  }
}
